version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nextcreaterapor-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextcreaterapor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextcreaterapor-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nextcreaterapor
    depends_on:
      - postgres

volumes:
  postgres_data: 